# Generated by Django 4.0.2 on 2022-04-24 08:08

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_content_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_upload',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
