# Generated by Django 4.0.2 on 2022-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_post_content_upload_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, default='images/5353134.png', null=True, upload_to='uploads'),
        ),
    ]
