# Generated by Django 4.0.2 on 2022-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='images/5353134.png', null=True, upload_to='uploads'),
        ),
    ]
