# Generated by Django 4.0.2 on 2022-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_userdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(blank=True, default='images/png-transparent-user-user-people-linear-icon-user-infographic-people-monochrome-thumbnail.png', upload_to='uploads'),
        ),
    ]
