# Generated by Django 4.0.2 on 2022-04-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userdetail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='image',
        ),
    ]
