# Generated by Django 4.0.2 on 2022-04-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_post_options_remove_userdetail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
